[project]
name = "recomm_town"
version = "2024.02.18"
requires-python = ">= 3.12"
dependencies = ["pyglet==2.0.10", "numpy", "PyYAML~=6.0"]
readme = "README.md"
license = {file = "LICENSE"}

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
