on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - run: pip install -e .
    - run: pip install pyinstaller
    - run: pyinstaller src/recomm.spec
    - uses: actions/upload-artifact@v2
      with:
        name: recomm-${{ matrix.os }}
        path: dist/*
